### ISSUE TITLE
Local install fails due to missing config file

### ISSUE THREAD

**Issue by raghothams** [tosdr/ToSBack3#8]
Local installation of the repo fails because of missing config file 

```
== Preparing database ==
rails aborted!
Cannot load database configuration:
Could not load database configuration. No such file - ["config/database.yml"]
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/configuration.rb:185:in `database_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:39:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/root/tosback3/bin/rails:9:in `require'
/root/tosback3/bin/rails:9:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/var/lib/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/root/tosback3/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Could not load database configuration. No such file - ["config/database.yml"]
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/configuration.rb:185:in `database_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:39:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/root/tosback3/bin/rails:9:in `require'
/root/tosback3/bin/rails:9:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/var/lib/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/root/tosback3/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==

```

**Comment by michielbdejong** [comment]
OK, @JimmStout can you have a look?

**Comment by raghothams** [comment]
I know `database.yml` is intentionally added to `.gitignore`. But someone you wants to setup this repo locally will fail to do so (esp. people new to ruby).

Here is a sample format, that should work for dev landscape - https://github.com/tosdr/ToSBack3/pull/15

**Comment by JustinBack** [comment]
We now have an example file in config/database.yml.example
